server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://101.132.190.67:3306/mail_demo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml